---
--- Generated by Luanalysis
--- Created by zhu.
--- DateTime: 2023/2/13 17:32
---
--在redis中拿到对应的锁的value，也就是锁标识，进行判断
if (redis.call("GET",KEYS[1])==ARGV[1]) then
    --判断一致则删除（释放锁） 返回1
    return redis.call("DEL",KEYS[1])
end
--说明锁标识不一致，返回0
return 0